changelog:
  exclude:
    authors:
      - dependabot
      - octocat
  categories:
    - title: Added
      labels:
        - Enhancement
    - title: Deprecated
      labels:
        - Deprecated
    - title: Removed
      labels:
        - Removed
    - title: Fixed
      labels:
        - Bug
    - title: Security
      labels:
        - Security
    - title: Changed
      labels:
        - "*"