# For more information: https://laravel.com/docs/sail
version: '3'
services:
    laravel.test:
        env_file: .env.example
    mysql:
        env_file: .env.example
    redis:
        env_file: .env.example
networks:
    sail:
        driver: bridge
volumes:
    sailmysql:
        driver: local
    sailredis:
        driver: local
