#!/usr/bin/env bash

shutdown() {
    if [ $(/usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:status | grep -q 'Octane server is running.') ]; then
        echo "Gracefully stopping Octane..."
        /usr/bin/php -d variables_order=EGPCS /var/www/html/artisan octane:stop
        echo "Sucessfully stopped Octane!"
    else
        echo "Octane is not running anymore, no need to stop it."
    fi

    # Make sure state is being removed
    rm /var/www/html/storage/logs/octane-server-state.json
}

# call shutdown() when exiting
trap shutdown EXIT SIGINT SIGTERM

echo "Starting Octane..."
/usr/bin/php -e -d yasd.open_extended_info=1 -d variables_order=EGPCS /var/www/html/artisan octane:start --server=swoole --host=0.0.0.0 --port=80