#!/usr/bin/env bash

# This command is the last of three that finalizes container setup when a dev container is created. 
# It happens after updateContentCommand and once the dev container has been assigned to a user for the first time.
#
# https://containers.dev/implementors/json_reference/#lifecycle-scripts

# Install dependencies in parallel
echo "Installing dependencies..."
(
    composer install & \
    npm install
)

# Migrate the database
echo "Migrating the database..."
./artisan migrate

# Install NPM dependencies and build assets
echo "Building assets..."
npm run dev
